<?

require_once('design.inc.php');

include('header.php');


print( "<a name=\"set\">" );


print_news_title("Set<br>");
  $txt  = "";
  $txt .= "<table border=\"0\" cellpadding=\"2\" cellspacing=\"1\" width=\"100%\">\n" ;
  $txt .= "    <tr class=\"head\">\n" ;
  $txt .= "      <td>Compos originales</td>\n" ;
  $txt .= "			<td>Reprises</td>\n" ;
  $txt .= "    </tr>\n" ;
  $txt .= "		<tr class=\"date\">\n" ;
  $txt .= "		  <td class=\"dateinfo\"><a href=\"zik.php#rageinwonderland\">Rage In Wonderland</a><br></td>\n" ;
  $txt .= "			<td class=\"dateinfo\"><a href=\"zik.php#toxicity\">Toxicity</a> / <a href=\"http://www.systemofadown.com\" target=\"_blank\">System of a Down</a></td>\n" ;
  $txt .= "  	</tr>\n" ;
  $txt .= "		<tr class=\"date\">\n" ;
  $txt .= "    	<td class=\"dateinfo\"><a href=\"zik.php#coupedumonde\">Coupé Du Monde</a></td>\n" ;
  $txt .= "      <td class=\"dateinfo\"><a href=\"zik.php#standbyme\">Stand by me</a> / Ben E. King</td>\n" ;
  $txt .= "  	</tr>\n" ;
  $txt .= "		<tr class=\"date\">\n" ;
  $txt .= "    	<td class=\"dateinfo\"><a href=\"zik.php#colours\">Colours</a></td>\n" ;
  $txt .= "      <td class=\"dateinfo\"><a href=\"zik.php#underthebridge\">Under the bridge</a> / <a href=\"http://www.redhotchilipeppers.com\" target=\"_blank\">Red Hot Chili Peppers</a></td>\n" ;
  $txt .= "  	</tr>\n" ;
  $txt .= "    <tr class=\"date\">\n" ;
  $txt .= "     	<td class=\"dateinfo\"><a href=\"zik.php#funkystorm\">The Funky Storm</a></td>\n" ;
  $txt .= "      <td class=\"dateinfo\"><a href=\"zik.php#pardonme\">Pardon me</a> / <a href=\"http://www.enjoyincubus.com\" target=\"_blank\">Incubus</a></td>\n" ;
  $txt .= "  	</tr>\n" ;
  $txt .= "    <tr class=\"date\">\n" ;
  $txt .= "     	<td class=\"dateinfo\"><a href=\"zik.php#encore1x\">Encore Une Fois</a></td>\n" ;
  $txt .= "      <td class=\"dateinfo\"><a href=\"zik.php#lovelyman\">My lovely man</a> / <a href=\"http://www.redhotchilipeppers.com\" target=\"_blank\">Red Hot Chili Peppers</a></td>\n" ;
  $txt .= "  	</tr>\n" ;
  $txt .= "    <tr class=\"date\">\n" ;
  $txt .= "		  <td class=\"dateinfo\"><a href=\"zik.php#onomatopee\">Onomatopée</a><br></td>\n" ;
  $txt .= "			<td class=\"dateinfo\">&nbsp;</td>\n" ;
  $txt .= "  	</tr>\n" ;
  $txt .= "    <tr class=\"date\">\n" ;
  $txt .= "		  <td class=\"dateinfo\">Phénomène De Mode<br></td>\n" ;
  $txt .= "			<td class=\"dateinfo\">&nbsp;</td>\n" ;
  $txt .= "  	</tr>\n" ;
  $txt .= "</table>\n" ;
print_news_content($txt);


print( "<a name=\"rageinwonderland\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Rage In Wonderland<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "<img alt=\"rage in wonderland\" src=\"data/rage.jpg\" height=\"100\" width=\"327\"><br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Hey, do you feel the light, shinning into your eyes, you know it is our pride, ouh-ouh.<br>\n" ;
  $txt .= "We are making all bad things, become a sun rising, in the darkness of life, ouh-ouh.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "You just wanna hang on,<br> \n" ;
  $txt .= "But you're still walking alone,<br>\n" ;
  $txt .= "So catch the rope we have thrown,<br>\n" ;
  $txt .= "Before you fall...<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "fall, fall, fall<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Hey, do you feel the light, shinning into your eyes, you know it is our pride, ouh-ouh.<br>\n" ;
  $txt .= "We are making all bad things, become a sun rising, in the darkness of life, ouh-ouh.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "We are ready to take off,<br>\n" ;
  $txt .= "To make you fly above all,<br>\n" ;
  $txt .= "And gently glide in the storm,<br>\n" ;
  $txt .= "Before we fall,<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "fall, fall, fall<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "We've fallen in wonderland, Eat mushrooms, take my hand, we're going to the mad funk-party.<br>\n" ;
  $txt .= "We've fallen in queen's garden, Eat mushrooms, take my herb, look at the twins and the kitty.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Hey, do you feel the light, shinning into your eyes, you know it is our pride, ouh-ouh.<br>\n" ;
  $txt .= "We are making all bad things, become a sun rising, in the darkness of life, ouh-ouh.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "We are falling from the skies<br>\n" ;
  $txt .= "We are falling from the skies<br>\n" ;
  $txt .= "We are falling from the skies<br>\n" ;
  $txt .= "We are falling from the skies<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Hey, do you feel the light, shinning into your eyes, you know it is our pride, ouh-ouh.<br>\n" ;
  $txt .= "We are making all bad things, become a sun rising, in the darkness of life, ouh-ouh.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Follow the rabbit,<br>\n" ;
  $txt .= "Follow the beat.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Fall, fall, fall<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 2002 - Funky Storm</td></tr></table>\n" ;
print_news_content($txt);


print( "<a name=\"coupedumonde\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Coupé Du Monde<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "<img alt=\"coupé du monde\" src=\"data/worldcut.jpg\" height=\"96\" width=\"400\"><br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Plongé dans mes songes, coupé du monde; je sens,<br>\n" ;
  $txt .= "Ce besoin profond de me mettre à l'ombre; je sais.<br>\n" ;
  $txt .= "Plongé dans mes songes, coupé du monde; je sens,<br>\n" ;
  $txt .= "Ce besoin profond de me mettre à l'ombre; je sais.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Sans cesse oppressé par l'ennui,<br>\n" ;
  $txt .= "Je distingue même plus les nuits.<br>\n" ;
  $txt .= "Si pour s'évader il faut rêver,<br>\n" ;
  $txt .= "Ne pas me réveiller.<br>\n" ;
  $txt .= "Folie ou partie de ma vie,<br>\n" ;
  $txt .= "Je n'ai plus l'envie.<br>\n" ;
  $txt .= "C'est au plus profond de mon âme,<br>\n" ;
  $txt .= "Que l'on m'entame.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Plongé dans mes songes, coupé du monde; je sens,<br>\n" ;
  $txt .= "Ce besoin profond de me mettre à l'ombre; je sais.<br>\n" ;
  $txt .= "Plongé dans mes songes, coupé du monde; je sens,<br>\n" ;
  $txt .= "Ce besoin profond de me mettre à l'ombre; je sais.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "La psychose d'un cercle vicieux,<br>\n" ;
  $txt .= "Me rend plus nerveux.<br>\n" ;
  $txt .= "Comment dois-je en faire abstraction,<br>\n" ;
  $txt .= "L'inhibition.<br>\n" ;
  $txt .= "Si pour s'évader faut rêver,<br>\n" ;
  $txt .= "Ne pas me réveiller.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Pourquoi ce combat perdu,<br>\n" ;
  $txt .= "Lutter contre une sensation.<br>\n" ;
  $txt .= "Lutter contre une sensation.<br>\n" ;
  $txt .= "Lutter contre une sensation.<br>\n" ;
  $txt .= "Lutter contre une sensation.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Plongé dans mes songes, coupé du monde; je sens,<br>\n" ;
  $txt .= "Ce besoin profond de me mettre à l'ombre; je sais.<br>\n" ;
  $txt .= "Plongé dans mes songes, coupé du monde; je sens,<br>\n" ;
  $txt .= "Ce besoin profond de me mettre à l'ombre; je sais.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 2002 - Funky Storm</td></tr></table>\n" ;
print_news_content($txt);
	

print( "<a name=\"colours\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Colours<br>");
  $txt  = "";
  $txt .= "<table border=\"0\" cellpadding=\"2\" cellspacing=\"6\" width=\"100%\"><tr><td valign=\"top\">\n" ;
  $txt .= "<img alt=\"colours\" src=\"data/colours.jpg\" height=\"408\" width=\"70\">\n" ;
  $txt .= "</td><td class=\"n2\">\n" ;
  $txt .= "Don't say anything<br>\n" ;
  $txt .= "It would be worst than better<br>\n" ;
  $txt .= "There's nobody on your side<br>\n" ;
  $txt .= "To believe in these words<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "It's a brand, brand new day in hell<br>\n" ;
  $txt .= "Throw away the shadows of your soul<br>\n" ;
  $txt .= "Kick it all, change the plans<br>\n" ;
  $txt .= "You need colours to start all over again<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Please show me better now<br>\n" ;
  $txt .= "It's not a game we play<br>\n" ;
  $txt .= "I hope it's over but your eyes<br>\n" ;
  $txt .= "Betray the feelings under<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "It's a brand, brand new day in hell<br>\n" ;
  $txt .= "Throw away the shadows of your soul<br>\n" ;
  $txt .= "Kick it all, change the plans<br>\n" ;
  $txt .= "You need colours to start all over again<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "This pain is not mine<br>\n" ;
  $txt .= "You can live your own way<br>\n" ;
  $txt .= "But in the darkness of your mind<br>\n" ;
  $txt .= "You won't find any answer<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "It's a brand, brand new day in hell<br>\n" ;
  $txt .= "Throw away the shadows of your soul<br>\n" ;
  $txt .= "Kick it all, change the plans<br>\n" ;
  $txt .= "You need colours to start all over again<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "It's a brand, brand new day in hell<br>\n" ;
  $txt .= "Throw away the shadows of your soul<br>\n" ;
  $txt .= "Kick it all, change the plans<br>\n" ;
  $txt .= "You need colours to start all over again<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "It's a brand, brand new day in hell<br>\n" ;
  $txt .= "Throw away the shadows of your soul<br>\n" ;
  $txt .= "Kick it all, change the plans<br>\n" ;
  $txt .= "You need colours to start all over again<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "It's a brand, brand new day in hell<br>\n" ;
  $txt .= "Throw away the shadows of your soul<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "</td></tr></table>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 2002 - Funky Storm</td></tr></table>\n" ;
print_news_content($txt);	


print( "<a name=\"funkystorm\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("The Funky Storm<br>");
  $txt  = "";
  $txt .= "<table border=\"0\" cellpadding=\"2\" cellspacing=\"6\" width=\"100%\"><tr><td class=\"n2\">\n" ;
  $txt .= "Heyyyyy ! Endolori par la vague de l'envie,<br>\n" ;
  $txt .= "Je suis flapi !<br>\n" ;
  $txt .= "Heyyyyy ! Découvrir un monde sans interdits,<br>\n" ;
  $txt .= "D'où je m'enfui !<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Funky Storm se fait une joie de vous prendre dans ses bras.<br>\n" ;
  $txt .= "Caresser le torse nu d'une musique reconnue.<br>\n" ;
  $txt .= "Laissez vous embobiner pour mieux nous apprécier.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Heyyyyy ! Endolori par la vague de l'envie,<br>\n" ;
  $txt .= "Je suis flapi !<br>\n" ;
  $txt .= "Heyyyyy ! Découvrir un monde sans interdits,<br>\n" ;
  $txt .= "D'où je m'enfui !<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Funky Storm se fait une joie de vous prendre dans ses bras.<br>\n" ;
  $txt .= "Caresser le torse nu d'une musique reconnue.<br>\n" ;
  $txt .= "Laissez vous embobiner pour mieux nous apprécier.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Heyyyyy ! Endolori par la vague de l'envie,<br>\n" ;
  $txt .= "Je suis flapi !<br>\n" ;
  $txt .= "Heyyyyy ! Découvrir un monde sans interdits,<br>\n" ;
  $txt .= "D'où je m'enfui !<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "En chaleur,<br>\n" ;
  $txt .= "On vibre à l'unisson !<br>\n" ;
  $txt .= "Pour t'avouer,<br>\n" ;
  $txt .= "Qu'on veux vous amadouer<br>\n" ;
  $txt .= "Et t'enrôler,<br>\n" ;
  $txt .= "Afin de vous exploiter...<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Heyyyyy ! Endolori par la vague de l'envie,<br>\n" ;
  $txt .= "Je suis flapi !<br>\n" ;
  $txt .= "Heyyyyy ! Découvrir un monde sans interdits,<br>\n" ;
  $txt .= "D'où je m'enfui !<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "</td><td valign=\"top\" align=\"right\">\n" ;
  $txt .= "<img alt=\"The F\" src=\"data/thefunky.jpg\" height=\"400\" width=\"100\">\n" ;
  $txt .= "</td></tr></table>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 2002 - Funky Storm</td></tr></table>\n" ;
print_news_content($txt);


print( "<a name=\"encore1x\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Encore Une Fois<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "<img alt=\"hot\" src=\"data/encore1f.jpg\" height=\"74\" width=\"450\"><br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Soupir chaud sur ta nuque dénudée<br>\n" ;
  $txt .= "J'ouvre les yeux ce matin d'été<br>\n" ;
  $txt .= "Je me sens encore enflammé<br>\n" ;
  $txt .= "Par ce qui entre nous s'est passé<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Juste avec toi<br>\n" ;
  $txt .= "Encore une fois <br>\n" ;
  $txt .= "Abuse de moi<br>\n" ;
  $txt .= "Encore, encore une fois<br>\n" ;
  $txt .= "Sinon... Sinon je bois<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Souvenir furtif de cette nuit<br>\n" ;
  $txt .= "Les draps sont en débris<br>\n" ;
  $txt .= "Cette fille Satan l'habite<br>\n" ;
  $txt .= "Elle m'a bien sucé ma vitalité<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Juste avec toi<br>\n" ;
  $txt .= "Encore une fois <br>\n" ;
  $txt .= "Abuse de moi<br>\n" ;
  $txt .= "Encore, encore une fois<br>\n" ;
  $txt .= "Sinon... Sinon je bois<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Je la vois encore qui s'enfuie<br>\n" ;
  $txt .= "Discrètement par l'entrebâillure<br>\n" ;
  $txt .= "Seul avec ma frustration<br>\n" ;
  $txt .= "Je t'aurais bien pété le fion<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Juste avec toi<br>\n" ;
  $txt .= "Encore une fois <br>\n" ;
  $txt .= "Abuse de moi<br>\n" ;
  $txt .= "Encore, encore une fois<br>\n" ;
  $txt .= "Sinon... Sinon je bois<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 2002 - Funky Storm</td></tr></table>\n" ;
print_news_content($txt);


print( "<a name=\"onomatopee\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Onomatopée<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "<center><img alt=\"yogurt\" src=\"data/yogurt.jpg\" height=\"135\" width=\"150\"></center><br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 2002 - Funky Storm</td></tr></table>\n" ;
print_news_content($txt);


print( "<a name=\"toxicity\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Toxicity (reprise)<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "Conversion, software version 7.0,<br>\n" ;
  $txt .= "Looking at life through the eyes of a tire hub,<br>\n" ;
  $txt .= "Eating seeds as a past time activity,<br>\n" ;
  $txt .= "The toxicity of our city, of our city,<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "New, what do you own the world&nbsp;?<br>\n" ;
  $txt .= "How do you own disorder, disorder,<br>\n" ;
  $txt .= "Now, somewhere between the sacred silence,<br>\n" ;
  $txt .= "Sacred silence and sleep,<br>\n" ;
  $txt .= "Somewhere, between the sacred silence and sleep,<br>\n" ;
  $txt .= "Disorder, disorder, disorder.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "More wood for their fires, loud neighbors,<br>\n" ;
  $txt .= "Flashlight reveries caught in the headlights of a truck,<br>\n" ;
  $txt .= "Eating seeds as a past time activity,<br>\n" ;
  $txt .= "The toxicity of our city, of our city,<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "New, what do you own the world&nbsp;?<br>\n" ;
  $txt .= "How do you own disorder, disorder,<br>\n" ;
  $txt .= "Now, somewhere between the sacred silence,<br>\n" ;
  $txt .= "Sacred silence and sleep,<br>\n" ;
  $txt .= "Somewhere, between the sacred silence and sleep,<br>\n" ;
  $txt .= "Disorder, disorder, disorder.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "New, what do you own the world&nbsp;?<br>\n" ;
  $txt .= "How do you own disorder,<br>\n" ;
  $txt .= "Now, somewhere between the sacred silence,<br>\n" ;
  $txt .= "Sacred silence and sleep,<br>\n" ;
  $txt .= "Somewhere, between the sacred silence and sleep,<br>\n" ;
  $txt .= "Disorder, disorder, disorder.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "When I became the sun,<br>\n" ;
  $txt .= "I shone life into the man's hearts,<br>\n" ;
  $txt .= "When I became the sun,<br>\n" ;
  $txt .= "I shone life into the man's hearts.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 2001 - System of a Down</td></tr></table>\n" ;
print_news_content($txt);


print( "<a name=\"standbyme\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Stand by me (reprise)<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "When the night has come<br>\n" ;
  $txt .= "And the lane is dark<br>\n" ;
  $txt .= "And the moon is the only light we'll see<br>\n" ;
  $txt .= "No I won't be afraid<br>\n" ;
  $txt .= "No I won't be afraid<br>\n" ;
  $txt .= "Just as long as you stand, stand by me<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "And darling , darling<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Oh now, now, stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "If the sky that we look upon<br>\n" ;
  $txt .= "Should tumble and fall<br>\n" ;
  $txt .= "And the mountain should crumble to the sea<br>\n" ;
  $txt .= "I won't cry, I won't cry<br>\n" ;
  $txt .= "No I won't shed a tear<br>\n" ;
  $txt .= "Just as long as you stand, stand by me<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "And darling, darling<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Whenever you're in trouble, won't you stand by me<br>\n" ;
  $txt .= "Oh now, now, stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "And darling, darling<br> \n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me<br>\n" ;
  $txt .= "Stand by me.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright Ben E. King</td></tr></table>\n" ;
print_news_content($txt);


print( "<a name=\"underthebridge\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Under the bridge (reprise)<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "Sometimes I feel<br>\n" ;
  $txt .= "Like I don't have a partner<br>\n" ;
  $txt .= "Sometimes I feel<br>\n" ;
  $txt .= "Like my only friend<br>\n" ;
  $txt .= "Is the city I live in<br>\n" ;
  $txt .= "The city of angels<br>\n" ;
  $txt .= "Lonely as I am<br>\n" ;
  $txt .= "Together we cry<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "I drive on her streets<br>\n" ;
  $txt .= "'Cause she's my companion<br>\n" ;
  $txt .= "I walk through her hills<br>\n" ;
  $txt .= "'Cause she knows who I am<br>\n" ;
  $txt .= "She sees my good deeds<br>\n" ;
  $txt .= "And she kisses me windy<br>\n" ;
  $txt .= "I never worry<br>\n" ;
  $txt .= "Now that is a lie<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "I don't ever want to feel<br>\n" ;
  $txt .= "Like I did that day<br>\n" ;
  $txt .= "Take me to the place I love<br>\n" ;
  $txt .= "Take me all the way<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "It's hard to believe<br>\n" ;
  $txt .= "That there's nobody out there<br>\n" ;
  $txt .= "It's hard to believe<br>\n" ;
  $txt .= "That I'm all alone<br>\n" ;
  $txt .= "At least I have her love<br>\n" ;
  $txt .= "The city she loves me<br>\n" ;
  $txt .= "Lonely as I am<br>\n" ;
  $txt .= "Together we cry<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "I don't ever want to feel<br>\n" ;
  $txt .= "Like I did that day<br>\n" ;
  $txt .= "Take me to the place I love<br>\n" ;
  $txt .= "Take me all that way<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Under the bridge downtown<br>\n" ;
  $txt .= "Is where I drew some blood<br>\n" ;
  $txt .= "Under the bridge downtown<br>\n" ;
  $txt .= "I could not get enough<br>\n" ;
  $txt .= "Under the bridge downtown<br>\n" ;
  $txt .= "Forgot about my love<br>\n" ;
  $txt .= "Under the bridge downtown<br>\n" ;
  $txt .= "I gave my life away<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 1991 - Red Hot Chili Peppers</td></tr></table>\n" ;
print_news_content($txt);


print( "<a name=\"pardonme\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("Pardon me (reprise)<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "Pardon me while I burst<br>\n" ;
  $txt .= "Pardon me while I burst<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "A decade ago, I never thought I would be.<br>\n" ;
  $txt .= "A twenty three on the verge of spontaneous combustion. Woe-is-me<br>\n" ;
  $txt .= "But I guess that it comes with the territory.<br>\n" ;
  $txt .= "An ominous landscape of never-ending calamity.<br>\n" ;
  $txt .= "I need you to hear. I need you to see.<br>\n" ;
  $txt .= "That I have had all I can take<br>\n" ;
  $txt .= "And exploding seems like a definite possibility<br>\n" ;
  $txt .= "To me<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "So Pardon me while I burst into flames.<br>\n" ;
  $txt .= "I've had enough of the world, and its people's mindless games<br>\n" ;
  $txt .= "So Pardon me while I burn, and rise above the flame<br>\n" ;
  $txt .= "Pardon me, pardon me. I'll never be the same.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Not, two days ago I was having a look in a book<br>\n" ;
  $txt .= "And I saw a picture of a guy fried up above his knees<br>\n" ;
  $txt .= "I said I can relate<br>\n" ;
  $txt .= "Cause lately I've been thinking of combustication as a welcomed vacation from.<br>\n" ;
  $txt .= "The burdens of the planet earth, like gravity, hypocrisy, and the perils of being in 3-D...<br>\n" ;
  $txt .= "And thinking so much differently.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Pardon me while I burst into flames.<br>\n" ;
  $txt .= "I've had enough of the world, and it's people's mindless games<br>\n" ;
  $txt .= "So pardon me while I burn, and rise above the flame<br>\n" ;
  $txt .= "Pardon me, pardon me. I'll never be the same.<br>\n" ;
  $txt .= "Never be the same...yeah.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Pardon me while I burst into flames.<br>\n" ;
  $txt .= "Pardon me, pardon me, pardon me.<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "So pardon me while I burst into flames.<br>\n" ;
  $txt .= "I've had enough of the world, and it's people's mindless games<br>\n" ;
  $txt .= "So pardon me while I burn, and rise above the flame<br>\n" ;
  $txt .= "Pardon me, pardon me. I'll never be the same.<br>\n" ;
  $txt .= "Pardon me, never be the same. Yeah<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 1999 - Incubus</td></tr></table>\n" ;
print_news_content($txt);


print( "<a name=\"lovelyman\">\n" );
print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>\n" );


print_news_title("My lovely man (reprise)<br>");
  $txt  = "";
  $txt .= "<br>\n" ;
  $txt .= "I used to shout<br>\n" ;
  $txt .= "Across the room to you<br>\n" ;
  $txt .= "And you'd come dancin'<br>\n" ;
  $txt .= "Like a fool<br>\n" ;
  $txt .= "Shuffle step<br>\n" ;
  $txt .= "You funky mother<br>\n" ;
  $txt .= "Come to me<br>\n" ;
  $txt .= "All warm as covers<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Rest with me<br>\n" ;
  $txt .= "My lovely brother<br>\n" ;
  $txt .= "For you see<br>\n" ;
  $txt .= "There is no other<br>\n" ;
  $txt .= "Memory so sad and sweet<br>\n" ;
  $txt .= "I'll see you soon<br>\n" ;
  $txt .= "Save me a seat<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Well I'm cryin'<br>\n" ;
  $txt .= "Now my lovely man<br>\n" ;
  $txt .= "Yes I'm cryin'<br>\n" ;
  $txt .= "Now and no one can<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "[chorus]<br>\n" ;
  $txt .= "Ever fill the<br>\n" ;
  $txt .= "The hole you left my man<br>\n" ;
  $txt .= "I'll see you later<br>\n" ;
  $txt .= "My lovely man if I can<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "In my room<br>\n" ;
  $txt .= "I'm all alone<br>\n" ;
  $txt .= "Waiting for you<br>\n" ;
  $txt .= "To get home<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Listen to Roberta Flack<br>\n" ;
  $txt .= "But I know you won't come back<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "[1/2 chorus]<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "Just in case<br>\n" ;
  $txt .= "You never knew<br>\n" ;
  $txt .= "I miss you slim<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "I love you too<br>\n" ;
  $txt .= "See my heart<br>\n" ;
  $txt .= "It's black and blue<br>\n" ;
  $txt .= "When I die<br>\n" ;
  $txt .= "I will find you<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "[chorus]<br>\n" ;
  $txt .= "<br>\n" ;
  $txt .= "<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\n" ;
  $txt .= "<tr><td class=\"copy2\">(c) Copyright 1991 - Red Hot Chili Peppers</td></tr></table>\n" ;
print_news_content($txt);


print( "<center><a href=\"zik.php#set\">Liste des compos</a><br><br></center>" );


include('footer.php');

?>
